name: Bater Ponto

on:
  schedule:
    - cron: "0 12 * * 1-5"
    - cron: "0 16 * * 1-5"
    - cron: "1 17 * * 1-5"
    - cron: "0 22 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          pip install --upgrade pip   # Upgrade pip to the latest version
          pip install poetry          # Install Poetry
          # Add Poetry to PATH
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
          echo "POETRY_HOME=$(poetry config virtualenvs.path)" >> $GITHUB_ENV

      - name: Verify Poetry installation
        run: poetry --version         # Verify that Poetry is installed correctly

      - name: Install dependencies
        run: poetry install           # Install dependencies from pyproject.toml
        env:
          POETRY_HOME: ${{ env.POETRY_HOME }}

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromedriver

      - name: Run Python script
        run: python3 scripts/script.py
