name: Bater Ponto

on:
  schedule:
    - cron: "0 12 * * 1-5"   # Executa às 09h:00 (UTC-3 convertido para UTC)
    - cron: "0 16 * * 1-5"   # Executa às 13h:00 (UTC-3 convertido para UTC)
    - cron: "1 17 * * 1-5"   # Executa às 14h:01 (UTC-3 convertido para UTC)
    - cron: "0 22 * * 1-5"   # Executa às 19h:00 (UTC-3 convertido para UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromedriver

      - name: Run Python script
        run: python3 scripts/script.py
