name: Bater Ponto

on:
  schedule:
    - cron: "0 12 * * 1-5"
    - cron: "0 16 * * 1-5"
    - cron: "1 17 * * 1-5"
    - cron: "0 22 * * 1-5"

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install Poetry
        run: |
          pip install --upgrade pip   # Ensure pip is up-to-date
          pip install poetry          # Install Poetry
          echo "::add-path::$(python -m site --user-base)/bin"  # Add Poetry to PATH

      - name: Verify Poetry installation
        run: poetry --version         # Verify that Poetry is installed correctly

      - name: Install dependencies
        run: poetry install           # Install dependencies from pyproject.toml

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromedriver

      - name: Run Python script
        run: python3 scripts/script.py
