name: Bater Ponto

on:
  schedule:
    - cron: "0 12 * * 1-5"   # Executa às 09h:00 (UTC-3 convertido para UTC)
    - cron: "0 16 * * 1-5"   # Executa às 13h:00 (UTC-3 convertido para UTC)
    - cron: "1 17 * * 1-5"   # Executa às 14h:01 (UTC-3 convertido para UTC)
    - cron: "0 22 * * 1-5"   # Executa às 19h:00 (UTC-3 convertido para UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Versão específica do Python para evitar problemas de compatibilidade

      - name: Cache Poetry
        uses: actions/cache@v2
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 - 
        shell: bash

      - name: Verify Poetry installation
        run: poetry --version

      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: ${{ runner.os }}-poetry-venv-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-venv-

      - name: Install dependencies
        run: poetry install  

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver (latest stable version)
        run: |
          LATEST_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Check script file
        run: |
          if [ ! -f scripts/script.py ]; then
            echo "script.py not found!"
            exit 1
          fi

      - name: Run Python script with WebDriver Manager
        run: python3 scripts/script.py
