name: Bater Ponto

on:
  schedule:
    - cron: "0 12 * * 1-5"   # Executa às 09h:00 (UTC-3 convertido para UTC)
    - cron: "0 16 * * 1-5"   # Executa às 13h:00 (UTC-3 convertido para UTC)
    - cron: "1 17 * * 1-5"   # Executa às 14h:01 (UTC-3 convertido para UTC)
    - cron: "0 22 * * 1-5"   # Executa às 19h:00 (UTC-3 convertido para UTC)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -  # Instala o Poetry
          echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV  # Adiciona o Poetry ao PATH para todo o job
          source $GITHUB_ENV  # Carrega as variáveis de ambiente
        shell: bash

      - name: Verify Poetry installation
        run: ~/.local/bin/poetry --version  # Verifica se o Poetry foi instalado corretamente

      - name: Install dependencies
        run: ~/.local/bin/poetry install  # Instala as dependências listadas no pyproject.toml

      - name: Install Google Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver (latest stable version)
        run: |
          # Obtém a última versão estável do ChromeDriver
          LATEST_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
          wget -N https://chromedriver.storage.googleapis.com/$LATEST_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Run Python script with WebDriver Manager
        run: ~/.local/bin/poetry run python scripts/script.py  # Executa o script Python com o WebDriver Manager
